### PR TITLE
Reworked In-Game UI

### PR DESCRIPTION
**Pull request by bma73**

### CODE REVIEW

**Comment by bma73** [comment]
Preview: https://bluecloudmirror.electronauts.net/

**Comment by nheidloff** [comment]
Bjoern, this looks pretty good. For some reason the recognition doesn't seem to work that well anymore. I'm not sure whether this has to do with the changed dimensions. I'm at a conference this week and will take a closer look at the beginning of next week. Thanks

**Comment by nheidloff** [comment]
Hi Björn, it seems to work for me here at home. Not sure why it didn't work that well earlier. We'll do some more testing.

Great job! The new UI looks awesome! Thanks a lot

**Comment by bma73** [comment]
Hi Niklas,
I'm glad you like it :-)
The captured image used for the recognition should be the same size as before.

**Comment by bma73** [comment]
Hi,
here's what I've updated:

- Added webcam preview to level intro view
- Display captured face/pose on success
- Updated result screen
- Updated button colors
- CSS fixes

- Added css file to score webapp

Preview: https://bluecloudmirror.electronauts.net/

**Comment by thomassuedbroecker** [comment]
Hello Björn, the new version looks fine. I like it ;-)
This request does include also the  new changes, as you wrote in you last comment right? 
Greetings, Thomas

**Pull request merged**
